const CONFIG={AUTO_REFRESH_MIN:10,NEWS_API:'/api/news',TIMEOUT:12000};
const CATEGORIES=['regional','world','technology','business','sports','health','science','entertainment'];
const LABELS={regional:'For Your Region',world:'World',technology:'Technology',business:'Business',sports:'Sports',health:'Health',science:'Science',entertainment:'Entertainment'};
const REGION_NAMES={US:'United States',GB:'United Kingdom',IN:'India',CA:'Canada',AU:'Australia',DE:'Germany',FR:'France',JP:'Japan',SG:'Singapore',AE:'United Arab Emirates'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let state={articles:[],active:'all',query:'',visible:6,hero:0,heroTimer:null,refreshTimer:null,first:true,region:null,settings:loadSettings()};
function loadSettings(){try{return {refreshMin:CONFIG.AUTO_REFRESH_MIN,regionOverride:'auto',notifications:true,...JSON.parse(localStorage.getItem('gnh_settings')||'{}')}}catch{return {refreshMin:10,regionOverride:'auto',notifications:true}}}
function saveSettings(){localStorage.setItem('gnh_settings',JSON.stringify(state.settings))}
function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function strip(s=''){const d=document.createElement('div');d.innerHTML=s;return(d.textContent||'').replace(/\s+/g,' ').trim()}
function ago(v){const d=new Date(v),n=(Date.now()-d)/1000;if(!isFinite(n))return'Recently';if(n<3600)return Math.max(1,Math.floor(n/60))+'m ago';if(n<86400)return Math.floor(n/3600)+'h ago';if(n<604800)return Math.floor(n/86400)+'d ago';return d.toLocaleDateString()}
function timeoutFetch(url,opt={},ms=CONFIG.TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return fetch(url,{...opt,signal:c.signal}).finally(()=>clearTimeout(t))}
async function detectRegion(){if(state.settings.regionOverride!=='auto'){const c=state.settings.regionOverride;return{code:c,name:REGION_NAMES[c]||c,source:'manual'}}const lang=navigator.languages?.[0]||navigator.language||'en-US',c=(lang.split('-')[1]||'').toUpperCase();return{code:c||'GLOBAL',name:REGION_NAMES[c]||'Global',source:'browser language'}}
function normalize(a,c){if(!a?.title||!a?.link)return null;return{...a,category:a.category||c,description:strip(a.description||''),image:a.image||''}}
async function fetchCategory(c){const region=state.region?.code||'GLOBAL';const r=await timeoutFetch(CONFIG.NEWS_API+'?category='+encodeURIComponent(c)+'&region='+encodeURIComponent(region)+'&t='+Date.now(),{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(c+' HTTP '+r.status);const d=await r.json();return(d.articles||[]).map(a=>normalize(a,c)).filter(Boolean)}
function merge(arr){return[...new Map(arr.map(a=>[a.id||a.link,a])).values()].sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate))}
function cache(){try{localStorage.setItem('gnh_cache',JSON.stringify({at:Date.now(),articles:state.articles.slice(0,350)}))}catch{}}
function cached(){try{const d=JSON.parse(localStorage.getItem('gnh_cache')||'{}');return d.at&&Date.now()-d.at<21600000?(d.articles||[]):[]}catch{return[]}}
async function loadAllNews({silent=false}={}){if(!silent){$('#loadingOverlay').hidden=false;$('#loadingText').textContent='Loading live headlines…'}const old=new Set(state.articles.map(a=>a.id));try{const results=await Promise.allSettled(CATEGORIES.map(fetchCategory));const fresh=results.filter(x=>x.status==='fulfilled').flatMap(x=>x.value);if(fresh.length){state.articles=merge(fresh);cache();renderAll();try{await detectNew(old)}catch(e){console.warn('Notification check failed',e)}toast('News updated','success')}else{const c=cached();if(c.length){state.articles=merge(c);renderAll();toast('Live feeds unavailable — showing cached headlines')}else{renderError()}}}catch(e){console.error('News load failed',e);const c=cached();if(c.length){state.articles=merge(c);renderAll()}else renderError()}finally{state.first=false;$('#loadingOverlay').hidden=true;$('#lastUpdated').textContent='Last updated: '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}
function filtered(){return state.articles.filter(a=>(state.active==='all'||a.category===state.active)&&(!state.query||(a.title+' '+a.description).toLowerCase().includes(state.query)))}
function imageMarkup(a,cls=''){return a.image?`<img class="${cls}" data-news-image src="${esc(a.image)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:`<span class="image-placeholder" aria-hidden="true">GNH</span>`}
function wireImages(root=document){$('img[data-news-image]',root).forEach(img=>img.addEventListener('error',()=>{const p=img.parentElement;img.remove();if(p&&!p.querySelector('.image-placeholder')){p.classList.add('image-missing');p.insertAdjacentHTML('afterbegin','<span class="image-placeholder" aria-hidden="true">GNH</span>')}}))}
function renderAll(){renderHero();renderTicker();renderSections();renderSidebars();renderRegion();wireImages()}
function renderHero(){clearInterval(state.heroTimer);const items=filtered().slice(0,5),box=$('#heroSlides'),dots=$('#heroDots');if(!items.length){box.innerHTML='<div class="empty">No featured stories available.</div>';dots.innerHTML='';return}state.hero=Math.min(state.hero,items.length-1);box.innerHTML=items.map((a,i)=>`<article class="hero-slide ${i===state.hero?'active':''}"><div class="hero-media">${imageMarkup(a,'hero-img')}</div><div class="hero-overlay"><span class="category-pill">${LABELS[a.category]}</span><h1>${esc(a.title)}</h1><p>${esc((a.description||'').slice(0,180))}</p><div class="meta">${esc(a.source||'News')} · ${ago(a.pubDate)}</div><a class="btn btn-primary" href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">Read full story</a></div></article>`).join('');dots.innerHTML=items.map((_,i)=>`<button type="button" class="${i===state.hero?'active':''}" data-hero="${i}" aria-label="Show story ${i+1}"></button>`).join('');$('[data-hero]').forEach(b=>b.onclick=()=>showHero(+b.dataset.hero));wireImages(box);state.heroTimer=setInterval(()=>showHero(state.hero+1),6000)}
function showHero(i){const items=filtered().slice(0,5);if(!items.length)return;state.hero=(i+items.length)%items.length;$$('.hero-slide').forEach((e,n)=>e.classList.toggle('active',n===state.hero));$$('[data-hero]').forEach((e,n)=>e.classList.toggle('active',n===state.hero))}
function renderTicker(){const recent=state.articles.filter(a=>Date.now()-new Date(a.pubDate)<12*3600000).slice(0,12);$('#tickerTrack').innerHTML=(recent.length?recent:state.articles.slice(0,12)).map(a=>`<a href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a><span>◆</span>`).join('')}
function card(a){return`<article class="news-card"><a class="card-image" href="${esc(a.link)}" target="_blank" rel="noopener noreferrer" aria-label="Read ${esc(a.title)}">${imageMarkup(a)}</a><div class="card-body"><div class="meta"><span>${esc(a.source||'News')}</span><span>${ago(a.pubDate)}</span></div><h3><a href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a></h3><p>${esc((a.description||'').slice(0,170))}</p><a class="read-link" href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">Read article</a></div></article>`}
function renderSections(){const root=$('#newsSections'),cats=state.active==='all'?CATEGORIES:[state.active];root.innerHTML=cats.map(c=>{const arr=state.articles.filter(a=>a.category===c&&(!state.query||(a.title+' '+a.description).toLowerCase().includes(state.query))).slice(0,state.visible);return`<section class="category-section" id="${c}"><div class="section-heading"><h2>${LABELS[c]}</h2><button data-cat="${c}">View category →</button></div><div class="news-grid">${arr.length?arr.map(card).join(''):'<div class="empty">No matching stories in this category.</div>'}</div></section>`}).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>selectCategory(b.dataset.cat))}
function sideItem(a){return`<a class="side-item" href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">${a.image?`<span class="side-thumb">${imageMarkup(a)}</span>`:''}<span><strong>${esc(a.title)}</strong><small>${esc(a.source||'News')} · ${ago(a.pubDate)}</small></span></a>`}
function renderSidebars(){const arr=filtered();$('#trendingList').innerHTML=arr.slice(0,6).map(sideItem).join('')||'<p class="muted">No stories yet.</p>';$('#recentList').innerHTML=state.articles.slice(0,6).map(sideItem).join('')||'<p class="muted">No stories yet.</p>'}
function renderRegion(){if(!state.region)return;$('#regionBadge').textContent='Region: '+state.region.name;$('#regionPanel').innerHTML=`<strong>${esc(state.region.name)}</strong><p>${state.region.city?esc(state.region.city)+' · ':''}Detected via ${esc(state.region.source)}.</p><p>Your region is used for context and can be overridden in Settings.</p>`}
function renderError(){$('#newsSections').innerHTML='<section class="error-panel"><h2>Headlines could not be loaded</h2><p>The news backend did not return articles. Check <code>/api/news?health=1</code> and redeploy the Netlify Function.</p><button class="btn btn-primary" id="retryBtn">Retry</button></section>';$('#retryBtn').onclick=()=>loadAllNews()}
function selectCategory(c){state.active=c;state.visible=6;$$('.category-tab').forEach(x=>x.classList.toggle('active',x.dataset.category===c));renderAll();$('#categoryNav').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false')}
function count(){return Number(localStorage.getItem('gnh_notification_count')||0)}
function updateCounter(){$('#notificationCounter').textContent=count()}
async function getSW(){if(!('serviceWorker'in navigator))return null;let r=await navigator.serviceWorker.getRegistration();if(!r)r=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});return navigator.serviceWorker.ready}
async function requestNotifications(){if(!('Notification'in window)){toast('Notifications are not supported');return false}if(!isSecureContext){toast('Notifications require HTTPS');return false}if(Notification.permission==='denied'){toast('Notifications are blocked. Use the site controls beside the address bar → Site settings → Notifications → Allow.');return false}let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();if(p!=='granted'){toast('Notification permission was not granted');return false}state.settings.notifications=true;saveSettings();$('#notificationBanner').hidden=true;try{const r=await getSW();await r.showNotification('Global News Hub notifications enabled',{body:'You will be alerted when new headlines arrive.',data:{url:location.href},tag:'gnh-test'})}catch{}toast('Notifications enabled','success');return true}
async function notify(a){if(!('Notification'in window)||!state.settings.notifications||Notification.permission!=='granted')return;const r=await getSW();await r.showNotification(a.title,{body:(a.source||'News')+' · '+(a.description||'').slice(0,120),data:{url:a.link},tag:'gnh-'+(a.id||a.link)});const n=count()+1;localStorage.setItem('gnh_notification_count',n);updateCounter()}
async function detectNew(old){const seenKey='gnh_seen';let saved=[];try{saved=JSON.parse(localStorage.getItem(seenKey)||'[]')}catch{}const seen=new Set(Array.isArray(saved)?saved:[]);const fresh=state.articles.filter(a=>!old.has(a.id)&&!seen.has(a.id)&&Date.now()-new Date(a.pubDate)<24*3600000);if(!state.first&&'Notification'in window&&Notification.permission==='granted')for(const a of fresh.slice(0,3))await notify(a);localStorage.setItem(seenKey,JSON.stringify(state.articles.slice(0,300).map(a=>a.id)))}
function schedule(){clearInterval(state.refreshTimer);state.refreshTimer=setInterval(()=>loadAllNews({silent:true}),Math.max(1,+state.settings.refreshMin||10)*60000)}
function toast(m,type=''){const e=document.createElement('div');e.className='toast '+type;e.textContent=m;$('#toastContainer').appendChild(e);setTimeout(()=>e.remove(),4200)}
function openSettings(){$('#refreshInterval').value=state.settings.refreshMin;$('#regionOverride').value=state.settings.regionOverride;const supported='Notification'in window;$('#notificationsToggle').checked=supported&&state.settings.notifications&&Notification.permission!=='denied';$('#notificationStatus').textContent=('Notification'in window)?'Browser permission: '+Notification.permission:'Notifications unsupported';$('#settingsModal').hidden=false}
function closeSettings(){$('#settingsModal').hidden=true;$('#settingsBtn').focus()}
function bind(){$('#heroPrev').onclick=()=>showHero(state.hero-1);$('#heroNext').onclick=()=>showHero(state.hero+1);$('#searchInput').oninput=e=>{state.query=e.target.value.toLowerCase().trim();renderAll()};$$('.category-tab').forEach(b=>b.onclick=()=>selectCategory(b.dataset.category));$('#menuToggle').onclick=()=>{const open=$('#categoryNav').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(open))};$('#loadMoreBtn').onclick=()=>{state.visible+=6;renderSections()};$('#settingsBtn').onclick=openSettings;$('#footerSettingsBtn').onclick=openSettings;$$('[data-close-modal]').forEach(x=>x.onclick=closeSettings);$('#allowNotificationsBtn').onclick=requestNotifications;$('#dismissNotificationsBtn').onclick=()=>{localStorage.setItem('gnh_banner','dismissed');$('#notificationBanner').hidden=true};$('#resetCounterBtn').onclick=()=>{localStorage.setItem('gnh_notification_count','0');updateCounter();toast('Notification counter reset','success')};$('#notificationsToggle').onchange=async e=>{if(e.target.checked){const ok=await requestNotifications();if(!ok)e.target.checked=false}else{state.settings.notifications=false;saveSettings()}};$('#saveSettingsBtn').onclick=async()=>{state.settings.refreshMin=+$('#refreshInterval').value;state.settings.regionOverride=$('#regionOverride').value;state.settings.notifications=$('#notificationsToggle').checked;saveSettings();schedule();state.region=await detectRegion();renderRegion();closeSettings();await loadAllNews();toast('Settings saved','success')};$$('[data-footer-category]').forEach(a=>a.onclick=e=>{e.preventDefault();selectCategory(a.dataset.footerCategory);scrollTo({top:0,behavior:'smooth'})})}
async function init(){document.body.classList.add('js-ready');$('#dateBadge').textContent='Date: '+new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});bind();updateCounter();try{await navigator.serviceWorker?.register('./service-worker.js',{updateViaCache:'none'})}catch{}state.region=await detectRegion();renderRegion();if('Notification'in window&&Notification.permission!=='granted'&&localStorage.getItem('gnh_banner')!=='dismissed')$('#notificationBanner').hidden=false;schedule();await loadAllNews()}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#settingsModal').hidden)closeSettings()});
document.addEventListener('DOMContentLoaded',init);
